models.py
from django.db import models

class Saloni(models.Model):
    NomeSalone = models.CharField(max_length = 30)
    Indirizzo = models.CharField(max_length = 50)
    Cittá = models.CharField(max_length = 40)
    Descrizione = models.CharField(max_length = 200)
    Immagine = models.ImageField()
    RecapitoTelefonico = models.CharField(max_length = 11)
    ORARI = (
            ('07:00:00', '07:00:00'),
            ('07:30:00', '07:30:00'),
            ('08:00:00', '08:00:00'),
            ('08:30:00', '08:30:00'),
            ('09:00:00', '09:00:00'),
            ('09:30:00', '09:30:00'),
            ('10:00:00', '10:00:00'),
            ('10:30:00', '10:30:00'),
            ('11:00:00', '11:00:00'),
            ('11:30:00', '11:30:00'),
            ('12:00:00', '12:00:00'),
            ('12:30:00', '12:30:00'),
            ('01:00:00', '01:00:00'),
            ('01:30:00', '01:30:00'),
            ('03:00:00', '03:00:00'),
            ('03:30:00', '03:30:00'),
            ('04:00:00', '04:00:00'),
            ('04:30:00', '04:30:00'),
            ('05:00:00', '05:00:00'),
            ('05:30:00', '05:30:00'),
            ('06:00:00', '06:00:00'),
            ('06:30:00', '06:30:00'),
            ('07:00:00', '07:00:00'),
            ('07:30:00', '07:30:00'),
            ('08:00:00', '08:00:00'),
            ('08:30:00', '08:30:00'),
    )
    OrarioAperturaMattino = models.CharField(max_length = 11, choices = ORARI)
    OrarioChiusurMattino = models.CharField(max_length = 11, choices = ORARI)
    OrarioAperturaPomeriggio = models.CharField(max_length = 11, choices = ORARI)
    OrarioChiusuraPomeriggio = models.CharField(max_length = 11, choices = ORARI)
    class Meta:
         verbose_name = "Salone"
         verbose_name_plural = "Saloni"
    def __str__(self):
        return self.NomeSalone

class Iva(models.Model):
    IVA = (
            ('22%', '22 Percento'),
    )
    Percentuale = models.CharField(max_length = 3, choices = IVA)
    class Meta:
         verbose_name = "Iva"
         verbose_name_plural = "Iva"
    def __str__(self):
        return self.Percentuale

class Trattamenti(models.Model):
    TipoTrattamento = models.CharField(max_length = 40)
    CostoEsentasse = models.PositiveIntegerField()
    IdIva = models.ForeignKey(Iva, null = True, on_delete=models.SET_NULL)
    Descrizione = models.TextField(max_length = 200)
    class Meta:
         verbose_name = "Trattamento"
         verbose_name_plural = "Trattamenti"
    def __str__(self):
        return self.TipoTrattamento

class Dipendenti(models.Model):
    Salone = models.ForeignKey(Saloni, null = True, on_delete=models.SET_NULL)
    Cognome = models.CharField(max_length = 30)
    Nome = models.CharField(max_length = 30)
    SEX = (
            ('F','Femmina'),
            ('M','Maschio'),
            ('U','Non sicuro'),
    )
    Sesso = models.CharField(max_length = 1, choices = SEX)
    DataNascita = models.DateField()
    Indirizzo = models.CharField(max_length = 50)
    RecapitoTelefonico = models.CharField(max_length = 11)
    Email = models.EmailField()
    DocumentoIdentitá = models.CharField(max_length = 9)
    class Meta:
         verbose_name = "Dipendente"
         verbose_name_plural = "Dipendenti"
    def __str__(self):
        return self.Cognome

class Clienti(models.Model):
    Cognome = models.CharField(max_length = 30)
    Nome = models.CharField(max_length = 30)
    SEX = (
            ('F','Femmina'),
            ('M','Maschio'),
            ('U','Non sicuro'),
    )
    Sesso = models.CharField(max_length = 1, choices = SEX)
    DataNascita = models.DateField()
    Indirizzo = models.CharField(max_length = 50)
    RecapitoTelefonico = models.CharField(max_length = 11)
    Email = models.EmailField()
    DocumentoIdentitá = models.CharField(max_length = 9)
    class Meta:
         verbose_name = "Cliente"
         verbose_name_plural = "Clienti"
    def __str__(self):
        return self.Cognome
       
class Appuntamenti(models.Model):
      Id_Salone = models.ForeignKey(Saloni,null = True, on_delete=models.SET_NULL)
      Id_Trattamento = models.ForeignKey(Trattamenti, null = True, on_delete=models.SET_NULL)
      Id_Dipendente = models.ForeignKey(Dipendenti, null = True, on_delete=models.SET_NULL)
      Data = models.DateField()
      Ora = models.TimeField()
      class Meta:
         verbose_name = "Appuntamento"
         verbose_name_plural = "Appuntamenti"
      def __str__(self):
        return self.Id_Salone.NomeSalone + "/" + str(self.Data) + "/" + str(self.Ora)

class FeedbackCliente(models.Model):
    Id_Appuntamento = models.ForeignKey(Appuntamenti, null = True, on_delete=models.CASCADE)
    STELLE = (
            ('1', '1 Stella'),
            ('2', '2 Stelle'),
            ('3', '3 Stelle'),
            ('4', '4 Stelle'),
            ('5', '5 Stelle'),

    )
    Stelle = models.CharField(max_length = 8, choices = STELLE)
    class Meta:
         verbose_name = "Feedback"
         verbose_name_plural = "Feedback"
    




templates/app/Contact.html
<!DOCTYPE html>

{% block contenuto %}

{% endblock %}

templates/app/GestioneSalone.html
<!DOCTYPE html>

 {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

<body>

    <div class="sfondo2" style="height: 100vh" id="Tabella">
         
        <div class="banner">
          <div class="navbarhome">
              <img src="{% static "app/Foto/Logo.png" %}" class="logo" style="width:7%; height:7%"/>
              <ul>
                  <li><a href="#"> Il Mio Salone </a></li>
                  <li><a href="#"> Contattaci </a></li>
                  <li><a href="#"> Il Mio Account</a></li>
              </ul>
          </div>
          <div class="contenthome" style="margin-top:15%; margin-inline:auto">
               <img src="{% static "app/Foto/Calendario.png" %}"/> 6 Maggio 
              
               <table class="bordered">
                    <tr>
                        <th><label>Nome</label></th>
                        <th><label>Orario Appuntamento</label></th>
                        <th><label>Trattamento</label></th>
                        <th><label>Costo</label></th>
                    </tr>
                    {% for appuntamento in appuntamenti %}
                        <tr>
                            <td><label>Da fare</label></td>
                            <td><label>{{appuntamento.Data}}</label></td>
                            <td><label>{{appuntamento.Id_Trattamento}}</label></td>
                            <td><label>15 €</label></td>
                        </tr>
                    {% endfor %}
                    </table>
              
              <div style="margin-left: -11px">
                    <a href={% url 'crea_appuntamento' %} class="button">Aggiungi Appuntamento</a>
                    <button type="button"><span></span> Rimuovi Appuntamento </button>
                    <button type="button"><span></span> Modifica Appuntamento </button>
              </div>
          </div>
      </div>


       
        

    </div>

    
</body>



 {% block contenuto %}
 {% endblock %}

templates/app/InformazioniSalone.html
<!DOCTYPE html>

 {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"/>

<body>
    
  




     <div style="height: 100vh" id="Home">
     
       
      <div class="banner font" style="  background-image: linear-gradient(rgba(0,0,0,0.75), rgba(0,0,0,0.75)), url({{saloni.Immagine.url}});">
          <div class="navbarhome">
              <img src="{% static "app/Foto/Logo.png" %}" class="logo" style="width:7%; height:7%"/>
              <ul>
                  <li><a href="#ChiSiamo"> Chi Siamo </a></li>
                  <li><a href="#Parrucchieri"> I Nostri Parrucchieri </a></li>
                  <li><a href="Contact/"> Contattaci </a></li>
                  <li><a href=""> Il Mio Account </a></li>
              </ul>
          </div>
          <div class="content"> 
              <h1>{{saloni.NomeSalone}}</h1>
              <p> {{saloni.Descrizione}}</p>
              <div>
                  <button type="button" onclick="location.href='{% url 'prenota' id=saloni.id %}'"><span></span> Prenota appuntamento </button>
              </div>
          </div>
      </div>

    </div>
    <div class="font row" id="ChiSiamo">
       <div class="col-8">
            <div style="margin-top:6%; margin-left:10%" class="col-8"> 
                 <a style="font-size: 66px; color: rgb(173 173 181);"> Chi siamo </a>
            </div>
            <div>
                <p style="margin-left: 10%; font-size: 25px; text-align: justify; max-width: 680px; padding-top: 42px">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, ssunt in culpa qui officia deserunt mollit anim id est laborum."</p>
            </div>
           <div style="margin-top: 15%; margin-left:10%; display: flex" class="content1">
                 <div style="font-size: 20px">
                        Per saperne di piú, Contattaci al numero {{saloni.RecapitoTelefonico}}. 
                            <button type="button"><span></span> Andiamo! </button>
                 </div>
           </div>
       </div>   
       <div style="text-align-last: end; margin-right: 3%;margin-left: inherit">
           <ul>
             <li class="responsive"><a href="#Home" style="color:#7A7A7A"> Torna Su! <img src="{%static "app/Foto/uparrow.png" %}" width="25" height="25" /></a></li>
           </ul>
       </div>
    </div>
    <div style = "margin-top:8%; text-align: -webkit-center;" class="font" id="Parrucchieri">
        <div>
            <div style="margin-top:3%; margin-left:70%"> 
                 <a style="font-size: 50px; color: rgb(173 173 181);"> I Nostri Parrucchieri </a>
            </div>
            <p style="margin-top: 20px; text-align: end; font-size: 22px; margin-right: 4%">Guarda i giudizi dei clienti sui nostri parrucchieri:</p>
        </div>  
        <div style="display: -webkit-inline-box; margin-top: 5%; justify-content: space-between">
          {% for dipendente in dipendenti %}
              <div class="card">
                  <div class="card-image1"></div>
                      <div class="card-text">
                        <h2>{{dipendente.Nome}}</h2>
                        <p>{{dipendente.RecapitoTelefonico}}</p>
                        <p>{{dipendente.Email}}</p>
                      </div>
                       <div class="card-stats">
                            <div class="stat">
                                  <div class="value">12<sup></sup></div>
                                  <div class="type">Clienti Abituali</div>
                            </div>
                           <div class="stat">
                                  <div class="value">3<sup></sup></div>
                                  <div class="type">Anni di Esperienza</div>
                            </div>
                            <div class="stat">
                                  <div class="value">Tutti</div>
                                  <div class="type">Numero Trattamenti</div>
                            </div>
                      </div>
                </div>
          {% endfor %}
           
        </div>

    </div>
       
  
</body>




 {% block contenuto %}
 {% endblock %}

templates/app/Saloni.html
<!DOCTYPE html>

{% block content %}

{% endblock %}

templates/app/about.html
<!DOCTYPE html>

{% block content %}

{% endblock %}


templates/app/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&family=Indie+Flower&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   

    
    <title></title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

</head>
<body>
    <div class="sfondo1" style="height: 100vh" id="Home">
     
       
      <div class="banner font">
          <div class="navbarhome">
              <img src="{% static "app/Foto/Logo.png" %}" class="logo" style="width:7%; height:7%"/>
              <ul>
                  <li><a href="#ChiSiamo"> Chi Siamo </a></li>
                  <li><a href="#Saloni"> Saloni </a></li>
                  <li><a href="Contact/"> Contattaci </a></li>
                  <li><a href={% url 'login_cliente' %}> Accedi come Cliente </a></li>
                  <li><a href={% url 'login' %}> Accedi come Barbiere </a></li>
                  <li><a href={% url 'login' %}> Registrati </a></li>
              </ul>
          </div>
          <div class="content">
              <h1>Gestisci il Tuo Salone</h1>
              <p> Oppure prendi appuntamento per usufruire dei nostri servizi!</p>
              <div>
                  <button type="button"><span></span> Spiegami meglio </button>
                  <button type="button"><span></span> Andiamo! </button>
              </div>
          </div>
      </div>

    </div>
    <div class="font row" id="ChiSiamo">
       <div class="col-8">
            <div style="margin-top:6%; margin-left:15%" class="col-8"> 
                 <a style="font-size: 66px"> Chi siamo </a>
            </div>
            <div>
                <p style="margin-left: 15%; font-size: 25px; text-align: justify; max-width: 680px; padding-top: 42px">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, ssunt in culpa qui officia deserunt mollit anim id est laborum."</p>
            </div>
           <div style="margin-top: 15%; margin-left:15%; display: flex" class="content1">
                 <div style="font-size: 20px">
                        Per saperne di piú, Contattaci. 
                            <button type="button"><span></span> Andiamo! </button>
                 </div>
           </div>
       </div>   
       <div style="max-width: max-content; margin: auto; text-align: center; margin-right: 12%" class="col-sm-4 responsive">
         <a style="font-size: 33px"> Seguici Su: </a> <br/>
            <a href="#" class="fa fa-facebook"></a>
            <a href="#" class="fa fa-google"></a>
            <a href="#" class="fa fa-linkedin"></a>
            <a href="#" class="fa fa-instagram"></a>
       </div>
       <div style="text-align-last: end; margin-right: 3%;margin-left: inherit">
           <ul>
             <li class="responsive"><a href="#Home" style="color:#7A7A7A"> Torna Su! <img src="{%static "app/Foto/uparrow.png" %}" width="25" height="25" /></a></li>
           </ul>
       </div>
    </div>
    <div style = "margin-top:8%" class="font" id="Saloni">
        <div>
            <div style="margin-top:3%; margin-left:74%"> 
                 <a style="font-size: 66px"> Saloni </a>
            </div>
            <p style="margin-top: 20px; text-align: end; font-size: 22px; margin-right: 16%">Guarda i nostri Saloni piú famosi e piú visitati:</p>
        </div>  
          <div style="display: flex; margin-top: 5%; justify-content: space-between">
          <div class="card">
              <div class="card-image1"></div>
                  <div class="card-text">
                    <h2>Salone 1</h2>
                    <p>Lorem ipsum dolor sit amet consectetur, Ducimus, repudiandae temporibus omnis illum maxime quod deserunt eligendi dolor</p>
                  </div>
                  <div class="card-stats">
                        <div class="stat">
                              <div class="value">4<sup>m</sup></div>
                              <div class="type">Clienti Abituali</div>
                        </div>
                        <div class="stat border">
                              <div class="value">13</div>
                              <div class="type">Parrucchieri</div>
                        </div>
                        <div class="stat">
                              <div class="value">32</div>
                              <div class="type">Numero Trattamenti</div>
                        </div>
                  </div>
            </div>
            <div class="card">
              <div class="card-image2"></div>
                  <div class="card-text">
                    <h2>Salone 2</h2>
                    <p>Lorem ipsum dolor sit amet consectetur, Ducimus, repudiandae temporibus omnis illum maxime quod deserunt eligendi dolor</p>
                  </div>
                  <div class="card-stats">
                        <div class="stat">
                              <div class="value">4<sup>m</sup></div>
                              <div class="type">Clienti Abituali</div>
                        </div>
                        <div class="stat border">
                              <div class="value">13</div>
                              <div class="type">Parrucchieri</div>
                        </div>
                        <div class="stat">
                              <div class="value">32</div>
                              <div class="type">Numero Trattamenti</div>
                        </div>
                  </div>
            </div>
            <div class="card">
              <div class="card-image3"></div>
                  <div class="card-text">
                    <h2>Salone 3</h2>
                    <p>Lorem ipsum dolor sit amet consectetur, Ducimus, repudiandae temporibus omnis illum maxime quod deserunt eligendi dolor</p>
                  </div>
                  <div class="card-stats">
                        <div class="stat">
                              <div class="value">4<sup>m</sup></div>
                              <div class="type">Clienti Abituali</div>
                        </div>
                        <div class="stat border">
                              <div class="value">13</div>
                              <div class="type">Parrucchieri</div>
                        </div>
                        <div class="stat">
                              <div class="value">32</div>
                              <div class="type">Numero Trattamenti</div>
                        </div>
                  </div>
            </div>
            <div class="card">
              <div class="card-image4"></div>
                  <div class="card-text">
                    <h2>Salone 4</h2>
                    <p>Lorem ipsum dolor sit amet consectetur, Ducimus, repudiandae temporibus omnis illum maxime quod deserunt eligendi dolor</p>
                  </div>
                  <div class="card-stats">
                        <div class="stat">
                              <div class="value">4<sup>m</sup></div>
                              <div class="type">Clienti Abituali</div>
                        </div>
                        <div class="stat border">
                              <div class="value">13</div>
                              <div class="type">Parrucchieri</div>
                        </div>
                        <div class="stat">
                              <div class="value">32</div>
                              <div class="type">Numero Trattamenti</div>
                        </div>
                  </div>
            </div>
       </div>
        
        
        
        
        
        
         <div style="text-align-last: end;">
           <ul>
             <li class="responsive"><a href="#Home" style="color:#7A7A7A"> Torna Su! <img src="{%static "app/Foto/uparrow.png" %}" width="25" height="25" /></a></li>
           </ul>
       </div>
    </div>
       

    



    {% block contenuto %}
    {% endblock %}

</body>
</html>

templates/app/creazione_appuntamento.html
{% load crispy_forms_tags %}

<html>



<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/forms.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/login.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"/>
</head>

<body>


   <div class="hero" style="background-image: linear-gradient(rgba(0,0,0,0.75), rgba(0,0,0,0.75)), url(../../static/app/Foto/unnamed.jpg); background-color: #009688; background-blend-mode: multiply">
     <div class="forme-box" style="border-radius: 15px; justify-items: center">
        <div class="row">
            <div class="col-8" style="max-width:900px; justify-content:center">
                <div style="margin-top:36px;width:100%; padding-top:2.5px">
                    <div class="container blank" style="width: max-content; color: black">
                        <h2 style="margin-top: unset"> Prenota un Appuntamento</h2>
                        <div style="margin-top: 67px">
                        <form method="post" enctype = "multipart/form-data">
                            {% csrf_token %}
                            {{ form.Id_Trattamento|as_crispy_field}}
                            <div id="div_id_Id_Dipendente" class="form-group">
                                    <label for="id_Id_Dipendente" class=" requiredField">
                                        Id Dipendente<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <select name="Id_Dipendente" class="select form-control" required="" id="id_Id_Dipendente">
                                        <option value="" selected="">---------</option>
                                            {% for dipendente in Dipendenti %}
                                                <option value="{{dipendente.pk}}">{{dipendente.Nome}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                            </div>
                            {{ form.Data|as_crispy_field }}
                            {{ form.Ora|as_crispy_field }}
                            <div style="text-align-last: center; margin-top: 40px">
                               <input type="submit" style="color: black !important; background-color: #009688 !important; border: 2px solid #000000 !important;" class="button" value = "Prenota" />
                             </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
    </div>

   

</body>
</html>
    

templates/app/home.html
<!DOCTYPE html>

{% extends 'app\base.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>

     {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

</head>
<body>

    {% block contenuto %}





    {% endblock %}

</body>
</html>

templates/app/index.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&family=Indie+Flower&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    
    <title></title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

</head>
<body>

   
</body>
</html>
    
   

       

templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>